tildes y typos arreglados
JavierJMelendez/hyperblog pull request #1
Opened 2022-12-09 04:36 UTC by JavierJMelendez

NO debimos pasar este error a master.

2022-12-10 03:06 UTC, javierjmelendezp requested changes
En vez de usar tildes directas, usar entidades HTML

2022-12-12 02:28 UTC, JavierJMelendez commented
Cambios solicitados ya fueron realizados, por favor, hazme el merge

2022-12-12 02:33 UTC, javierjmelendezp commented
Excelente!. Estoy conforme con lo realizado

2022-12-12 02:36 UTC, javierjmelendezp reviewed
excelente 2

2022-12-12 02:40 UTC, merged